# Generated by Django 3.2.9 on 2021-11-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='spookyLevel',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
